### ISSUE TITLE
How to change a single option of the objective funtion?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#103]
Trying this:

```
piConfiguration <- PIConfiguration$new()
piConfiguration$objectiveFunctionOptions$objectiveFunctionType <- "lsq"
```

throws an error

```
Error in validateIsOption(inputOptions, ObjectiveFunctionOptions) : 
  logScaleSD must be a single numeric value.
3.
stop(paste(messages, collapse = "\n")) at utilities-helper.R#65
2.
validateIsOption(inputOptions, ObjectiveFunctionOptions) at PIConfiguration.R#67
1.
(function (inputOptions = list())
{
if (missing(inputOptions)) {
private$.objectiveFunctionOptions ...

```

**Comment by PavelBal** [comment]
Add a test for this use case.

**Comment by rengelke** [comment]
Implementing option validation for objectiveFunctionOptions revealed a limitation with active bindings: modifying individual fields does not invoke the setter function, making it problematic to run the validation logic. There is also no simple way to intercept changes to individual list elements in order to trigger validation.
I think we have two options: 
(1) since direct modification seems to be common in ospsuite, we could remove this direct validation functionality and validate (throw meaningful error messages to users) later, e.g., within ParameterIdentification$run().
(2) keep the validation, but require that configurations are made through active binding using a named list of options.

**Comment by PavelBal** [comment]
Can `objectiveFunctionOptions` be another R6 class with pre-defined fields? You could then implement validations within this class.

**Comment by PavelBal** [comment]
- Validate in PI on calling `$run()`
